/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package money

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertEquals

class AppTest {
    @Test fun testMultiplication() {
        val five = Doller(5)
        five.times(2)
        assertEquals(10, five.amount)
    }
}
