/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package money

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse

class AppTest {
    @Test fun testMultiplication() {
        val five = Doller(5)
        assertEquals(Doller(10), five.times(2))
        assertEquals(Doller(15), five.times(3))
    }

    @Test fun testEquality() {
        assertTrue(Doller(5).equals(Doller(5)))
        assertFalse(Doller(5).equals(Doller(6)))
    }
}
