/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package money

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

data class Doller(var amount: Int){ // TODO limit scope
    fun times(multiplier: Int): Doller = Doller(amount * multiplier)
}

fun main(args: Array<String>) {
    println(App().greeting)
}
